### ISSUE TITLE
Invalid Type Read: The type 'bundle' does not exist.' to dictionary.

### ISSUE THREAD

**Issue by priamai** [os-threat/Stix-ORM#4]
Hi guys,
i don't think we thought about this use case but we need to implement a bundle retrieval method too:

```
import logging
from stix.module.authorise import import_type_factory
from stix.module.typedb import TypeDBSink,TypeDBSource
from stix.module.typedb_lib.instructions import ResultStatus
import json

logging.basicConfig(level=logging.INFO, format='[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s')
logger = logging.getLogger(__name__)

# define the database data and import details
connection = {
    "uri": "localhost",
    "port": "1729",
    "database": "stix",
    "user": None,
    "password": None
}
import_type = import_type_factory.get_default_import()

sink = TypeDBSink(connection=connection,
                    clear=True,
                    import_type=import_type)

source = TypeDBSource(connection=connection,import_type=import_type)

with open('./data/threat_actor_identity.json','r') as file:
    bundle_dict = json.load(file)
    results = sink.add(bundle_dict)
    ins_ids = []
    for result in results:
        logger.info(f"Inserted object {result.id}")
        logger.info(f"Status {result.status}")
        ins_ids.append(result.id)
    # now retrieve the objects inserted
    for id in ins_ids:
        obj = source.get(id)
        logger.info(f"STIX type = {obj.type} and id = {obj.id}")

    # can we get the entire bundle object?
    bundle_ret = source.get(bundle_dict['id'])

    print(bundle_ret)

```

Error:
```

[2023-03-09 22:33:47,898] ERROR [stix.module.typedb:691] Cannot convert '[TYR03] Invalid Type Read: The type 'bundle' does not exist.' to dictionary.
Traceback (most recent call last):
  File "/home/robomotic/DevOps/github/Stix-ORM/docs/interactions/python_api/load_bundles.py", line 40, in <module>
    bundle_ret = source.get(bundle_dict['id'])
  File "/home/robomotic/DevOps/github/Stix-ORM/stix/module/typedb.py", line 692, in get
    raise Exception(str(result.failure()))
Exception: Cannot convert '[TYR03] Invalid Type Read: The type 'bundle' does not exist.' to dictionary.
```

I also get side errors like this ones:
```

[2023-03-09 22:33:46,311] WARNING [stix.module.orm.export_object:455]  make standard relations visited, but not implemented
[2023-03-09 22:33:46,314] ERROR [stix.module.typedb:668] <IO: Object of type ThreatActor is not JSON serializable>
[2023-03-09 22:33:46,314] INFO [__main__:37] STIX type = threat-actor and id = threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428
[2023-03-09 22:33:46,803] WARNING [stix.module.orm.export_object:455]  make standard relations visited, but not implemented
[2023-03-09 22:33:46,806] ERROR [stix.module.typedb:668] <IO: Object of type Identity is not JSON serializable>
[2023-03-09 22:33:46,806] INFO [__main__:37] STIX type = identity and id = identity--733c5838-34d9-4fbf-949c-62aba761184c
[2023-03-09 22:33:47,544] ERROR [stix.module.typedb:668] <IO: Object of type Relationship is not JSON serializable>
[2023-03-09 22:33:47,544] INFO [__main__:37] STIX type = relationship and id = relationship--a2e3efb5-351d-4d46-97a0-6897ee7c77a0
```

**Comment by brettforbes** [comment]
the bundls cannot be stored as it is transient
https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_gms872kuzdmg

**Comment by priamai** [comment]
Yes I know but in terms of user experience it will be required. Maybe we store that information in a separate database if we need to decouple the official practices from the practical requirements ?

**Comment by brettforbes** [comment]
Ok, lets put on hold for the moment as there are issues with the IoB definition anyway. We can do easily after case/feed management

**Comment by priamai** [comment]
I agree sir!
